### ISSUE TITLE
java.lang.NoSuchMethodError: com.amazonaws.ClientConfiguration.withRetryPolicy

### ISSUE THREAD

**Issue by Hiroki11x** [Hiroki11x/SoraPractice#2]
AmazonDynamoDBClient client = new AmazonDynamoDBClient(new BasicAWSCredentials("AWS_ACCESS_KEY_ID", "yourSecretAccessKey"));
                client.setEndpoint("http://localhost:8000");

みたいにしようとしても

Exception in thread "main" java.lang.NoSuchMethodError: com.amazonaws.ClientConfiguration.withRetryPolicy(Lcom/amazonaws/retry/RetryPolicy;)Lcom/amazonaws/ClientConfiguration;
    at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClientConfigurationFactory.getDefaultConfig(AmazonDynamoDBClientConfigurationFactory.java:31)
    at com.amazonaws.ClientConfigurationFactory.getConfig(ClientConfigurationFactory.java:36)
    at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.<init>(AmazonDynamoDBClient.java:311)
    at dynamo.DynamodbSample01$DynamoUtils.setupDynamoClientConnection(DynamodbSample01.java:72)
    at dynamo.DynamodbSample01.main(DynamodbSample01.java:48)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

って言われる

**Comment by Hiroki11x** [comment]
http://hacknote.jp/archives/18779/
を試したら上記のエラーが出た

awsのsdkのバージョンをあげると(以下のように)

```
<dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk</artifactId>
            <version>1.11.46</version>
        </dependency>

        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-dynamodb</artifactId>
            <version>1.11.46</version>
        </dependency>
```

今度は

https://github.com/Hiroki11x/SoraPractice/issues/4

の問題に発展
